# Generated by Django 5.2 on 2026-08-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_assign_default_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(verbose_name='Face embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Face ID',
                'verbose_name_plural': 'Employee Face IDs',
            },
        ),
    ]
