# Generated by Django 5.2 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0015_alter_roster_department"),
        ("joydigi_audit", "0003_alter_historytrackingfields_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_name", models.CharField(max_length=255, verbose_name="Người thao tác")),
                ("actor_email", models.EmailField(blank=True, max_length=254, verbose_name="Thư điện tử")),
                ("role", models.CharField(choices=[("admin", "Quản trị viên"), ("leader", "Trưởng nhóm"), ("employee", "Nhân viên")], db_index=True, default="employee", max_length=20, verbose_name="Vai trò")),
                ("action", models.CharField(max_length=255, verbose_name="Thao tác")),
                ("resource", models.CharField(blank=True, max_length=255, verbose_name="Chức năng")),
                ("method", models.CharField(db_index=True, max_length=10, verbose_name="Phương thức")),
                ("path", models.CharField(max_length=500, verbose_name="Đường dẫn")),
                ("route_name", models.CharField(blank=True, max_length=150, verbose_name="Tên đường dẫn")),
                ("status_code", models.PositiveSmallIntegerField(default=200, verbose_name="Kết quả")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True, verbose_name="Địa chỉ mạng")),
                ("user_agent", models.CharField(blank=True, max_length=500, verbose_name="Thiết bị")),
                ("duration_ms", models.PositiveIntegerField(default=0, verbose_name="Thời gian xử lý (ms)")),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="Chi tiết")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Thời điểm")),
                ("company", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="user_activity_logs", to="base.company", verbose_name="Công ty")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="activity_logs", to=settings.AUTH_USER_MODEL, verbose_name="Tài khoản")),
            ],
            options={
                "verbose_name": "Nhật ký hoạt động",
                "verbose_name_plural": "Nhật ký hoạt động",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(fields=["company", "-created_at"], name="activity_company_time"),
                    models.Index(fields=["user", "-created_at"], name="activity_user_time"),
                ],
            },
        ),
    ]
