# Generated by Django 5.2 on 2026-08-20 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_companyleaves_company_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim đầu bảng tin'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_notification',
            field=models.BooleanField(default=True, verbose_name='Gửi thông báo trên ứng dụng'),
        ),
        migrations.CreateModel(
            name='CheckInLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=100, verbose_name='Tên địa điểm')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Kinh độ')),
                ('radius_meters', models.PositiveIntegerField(default=200, verbose_name='Bán kính cho phép (mét)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_locations', to='base.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Địa điểm chấm công',
                'verbose_name_plural': 'Địa điểm chấm công',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CheckInPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('late_threshold_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='Ngưỡng đi muộn (phút)')),
                ('annual_leave_days', models.PositiveSmallIntegerField(default=12, verbose_name='Số ngày phép mỗi năm')),
                ('allow_remote', models.BooleanField(default=True, verbose_name='Cho phép làm từ xa')),
                ('allow_outside_radius_request', models.BooleanField(default=True, verbose_name='Cho phép gửi đơn khi ở ngoài bán kính')),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_policy', to='base.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Quy định chấm công',
                'verbose_name_plural': 'Quy định chấm công',
            },
        ),
        migrations.CreateModel(
            name='OfficeWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mạng Wifi')),
                ('ssid', models.CharField(max_length=100, verbose_name='Tên Wifi hiển thị')),
                ('bssid', models.CharField(blank=True, help_text='Có thể để trống nếu không cần giới hạn đúng thiết bị phát.', max_length=17, verbose_name='Mã thiết bị phát Wifi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_wifi_networks', to='base.company', verbose_name='Công ty')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Wifi văn phòng',
                'verbose_name_plural': 'Wifi văn phòng',
                'ordering': ('name',),
            },
        ),
    ]
