# Generated by Django 5.2 on 2026-08-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joydigi_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joydigiuser',
            name='session_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
