# Generated by Django 5.2 on 2026-08-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_employee_self_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecords',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
