# Generated by Django 5.2 on 2026-08-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendancelateearlyrequest'),
        ('attendance', '0009_workrecords_message_max_length_100'),
    ]

    operations = [
    ]
