# Generated by Django 5.2 on 2026-08-26 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_overtimerequest'),
        ('employee', '0008_employeeface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceExplanationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('request_type', models.CharField(choices=[('missing_check_in', 'Missing Check-in'), ('missing_check_out', 'Missing Check-out'), ('late_arrival', 'Late Arrival'), ('early_leave', 'Early Leave'), ('other', 'Other')], max_length=32, verbose_name='Request Type')),
                ('request_date', models.DateField(verbose_name='Request Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('canceled', models.BooleanField(default=False, verbose_name='Canceled')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explanation_requests', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Explanation Request',
                'verbose_name_plural': 'Attendance Explanation Requests',
                'ordering': ['-id'],
                'permissions': (('approve_attendanceexplanationrequest', 'Approve Attendance Explanation Request'), ('cancel_attendanceexplanationrequest', 'Cancel Attendance Explanation Request')),
            },
        ),
    ]
