# Generated by Django 5.2 on 2026-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_remoteworkrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkout_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Checkout Count'),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='checkout_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Checkout Count'),
        ),
    ]
