# Generated by Django 5.2 on 2026-09-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendance_checkout_count_and_more'),
        ('base', '0016_add_announcement_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=16, verbose_name='Action')),
                ('attendance_mode', models.CharField(choices=[('OFFICE', 'Office'), ('REMOTE', 'Remote')], max_length=16, verbose_name='Attendance Mode')),
                ('method', models.CharField(blank=True, choices=[('WIFI', 'Wi-Fi'), ('LOCATION', 'Location'), ('QR', 'QR'), ('NUMERIC_CODE', 'Numeric Code'), ('FACE', 'Face')], max_length=16, null=True, verbose_name='Method')),
                ('wifi_ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Wi-Fi SSID')),
                ('wifi_bssid', models.CharField(blank=True, max_length=17, null=True, verbose_name='Wi-Fi BSSID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Accuracy (m)')),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Distance (m)')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('captured_at', models.DateTimeField(verbose_name='Captured At')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='attendance.attendance', verbose_name='Attendance')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_evidences', to='base.checkinlocation', verbose_name='Nearest Location')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('remote_work_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_evidences', to='attendance.remoteworkrequest', verbose_name='Remote Work Request')),
            ],
            options={
                'verbose_name': 'Attendance Evidence',
                'verbose_name_plural': 'Attendance Evidence',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('attendance', 'action'), name='unique_attendance_evidence_per_action')],
            },
        ),
    ]
